version: '3.9'

services:
    techtask-db:
        container_name: techtask-db
        image: postgres:15.2-alpine
        restart: always
        healthcheck:
            test: [ "CMD", "pg_isready", "-q" ]
        ports:
            - "7778:5432"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - 'db_data:/var/lib/postgresql/data'
        networks:
            - backend

volumes:
    db_data:

networks:
    backend:
        driver: bridge
